dist: trusty
language: c
compiler: gcc
cache: ccache
env:
  global:
   - TERM=dumb
addons:
   apt:
      packages:
        - bc 
        - wget
        - git
        - diffstat
        - makeinfo
        - chrpath 
script:
        - bash -ex build.sh

