dist: trusty
language: c
compiler: gcc
cache: ccache
sudo: required
env:
  global:
   - TERM=dumb
addons:
   apt:
      packages:
        - bc 
        - wget
        - git
        - diffstat
        - texinfo
        - chrpath 
script:
        - bash -ex build.sh

